"""Concept explanation module.

As described in the project document, explanations can be generated by the lightweight
local model LaMini-Flan-T5-783M (runs on CPU / Apple Silicon, no API cost). Because that
model needs `transformers` + `torch` (~2-3 GB download), it is optional:

    EXPLAIN_BACKEND=auto    (default) use the local model if transformers/torch are
                            installed, otherwise - or if it fails - use Gemini
    EXPLAIN_BACKEND=local   always use the local model (falls back to Gemini on error)
    EXPLAIN_BACKEND=gemini  always use Gemini

Install the local model dependencies with:  pip install -r requirements-local.txt
"""

from __future__ import annotations

import importlib.util
import logging
import os
import threading

import gemini_client

logger = logging.getLogger("edugenie.explain")

LOCAL_MODEL_NAME = os.getenv("LOCAL_EXPLAIN_MODEL", "MBZUAI/LaMini-Flan-T5-783M")

EXPLAIN_PROMPT = """Explain the concept of '{topic}' in a simple and clear way for a school student.
Use short sentences, an everyday analogy, and one small example. Finish with a one-line
"Key takeaway". Keep it under 200 words."""

_model_lock = threading.Lock()
_explain_tokenizer = None
_explain_model = None


def get_backend() -> str:
    backend = os.getenv("EXPLAIN_BACKEND", "auto").strip().lower()
    return backend if backend in {"auto", "local", "gemini"} else "auto"


def local_model_available() -> bool:
    """True when the optional transformers/torch dependencies are installed."""
    return all(importlib.util.find_spec(m) is not None for m in ("transformers", "torch"))


def _load_local_model():
    """Load LaMini-Flan-T5 once (thread-safe). Downloads it on first use."""
    global _explain_tokenizer, _explain_model
    if _explain_model is None:
        with _model_lock:
            if _explain_model is None:
                from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

                logger.info("Loading local explanation model %s (first run downloads it)...", LOCAL_MODEL_NAME)
                _explain_tokenizer = AutoTokenizer.from_pretrained(LOCAL_MODEL_NAME)
                _explain_model = AutoModelForSeq2SeqLM.from_pretrained(LOCAL_MODEL_NAME)
                _explain_model.eval()
                logger.info("Local explanation model loaded.")
    return _explain_tokenizer, _explain_model


def explain_with_local_model(topic: str) -> str:
    import torch

    tokenizer, model = _load_local_model()
    input_text = f"Explain the concept of '{topic}' in a simple and clear way for a school student."
    inputs = tokenizer(input_text, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.7,
            top_k=50,
            top_p=0.95,
            do_sample=True,
        )
    return tokenizer.decode(outputs[0], skip_special_tokens=True).strip()


def explain_with_gemini(topic: str) -> str:
    return gemini_client.generate(EXPLAIN_PROMPT.format(topic=topic), temperature=0.5)


def explain_topic(topic: str) -> tuple[str, str]:
    """Return (explanation, source) where source is "local" or "gemini".

    Raises gemini_client.GeminiError if every available backend fails.
    """
    topic = topic.strip()
    backend = get_backend()

    if backend == "local" or (backend == "auto" and local_model_available()):
        try:
            explanation = explain_with_local_model(topic)
            if explanation:
                return explanation, "local"
        except Exception:
            logger.exception("Local explanation model failed; falling back to Gemini")

    return explain_with_gemini(topic), "gemini"


def preload() -> None:
    """Optionally warm up the local model at server start (PRELOAD_LOCAL_MODEL=true)."""
    if get_backend() != "gemini" and local_model_available():
        try:
            _load_local_model()
        except Exception:
            logger.exception("Could not preload the local explanation model")
